### ISSUE TITLE
Markdown not rendering properly

### ISSUE THREAD

**Issue by Wferr** [Paradox2102/paradox2102.github.io#11]
Might have to do with the Jekyll update.

**Comment by Wferr** [comment]
Renders locally on my instance perfectly but in GitHub it doesn't.

**Comment by ohmeow** [comment]
What files are you talking about?

**Comment by ohmeow** [comment]
Ok I see it now.

Works fine for me locally so I suspect something is going on with the automated build process when deployed to git ... I even wonder if it is related to the problems I was having with inline javascript comments.  Most of the markdown works fine, its the header markdown (e.g. ###, ####, etc..) that aren't rendering properly ... and as you know, "#" is what you use for inline comments in ruby.

So, I would disable all the compression and minification features on production and see if then things start working.

**Comment by Wferr** [comment]
@wgpubs Jekyll would first render the markdown before it even gets to the compression level of the code. So I doubt that is it. Im going to try to build production site locally and see what happens.

**Comment by ohmeow** [comment]
hmmm ... anything interesting being done during the build process???

**Comment by Wferr** [comment]
Nope looks all proper on my end and Github isnt throwing any errors at me.

**Comment by ohmeow** [comment]
Yah ... works fine for me locally too.

**Comment by ohmeow** [comment]
What about telling the site to use Github's flavor of markup explicitly?

```
kramdown:
  input: GFM
```

**Comment by Wferr** [comment]
Still doesn't want to render it.

**Comment by ohmeow** [comment]
What happens if you change the extension from .markdown to .md?

-wg

**Comment by Wferr** [comment]
they are all named .md currently not .markdown

**Comment by ohmeow** [comment]
looking on my phone this morning. all the markdown is rendering fine.

**Comment by Wferr** [comment]
I added spaces in front of them. Before it was like `##Text` and now its like `## Text` that seemed to fix it.

**Comment by ohmeow** [comment]
ah. I was wondering about that but as it worked locally I thought that
couldn't be it. anyways, cool.

**Comment by Wferr** [comment]
Yeah strange how it rendered fine locally. Apparently githubs flavor of kramdown doesnt like that.

**Comment by selfiequeen666** [comment]
hey guys u graduated two years ago, could you please take me off the mailing list?

**Comment by Wferr** [comment]
@selfiequeen666 You are already removed from the organisation. I do not have the power to remove you from the repository. You can either disable GitHub emails or the better option would be to login to Github and "Unwatch" the repository.
