### ISSUE TITLE
Improve Footer.

### ISSUE THREAD

**Issue by Wferr** [Paradox2102/paradox2102.github.io#14]
Add more content and more useful things to the footer.

**Comment by ohmeow** [comment]
consider putting social links there so they are accessible on all pages.
also need someone to start putting events in Google calendar.

**Comment by Wferr** [comment]
Commit 15a4c4420e78b652e55c437f59dff5b1ded7ddd9 changed it a bit. Need to match colors somehow. Not sure what color to use. But the grey doesnt fit in.

**Comment by Wferr** [comment]
Also not sure if this commit caused it or not but if scrolled to bottom of page and refreshing the navbar sometimes sticks to the bottom of the page.
