### ISSUE TITLE
Blue is too Blue

### ISSUE THREAD

**Issue by ghost** [Paradox2102/paradox2102.github.io#2]
The blue color of the background is too viberant... please make it a better shade.

**Comment by Wferr** [comment]
Any suggestions for color?

**Comment by ghost** [comment]
you might be able to go with a cool navy blue like the jackets

**Comment by cstill** [comment]
Hex #42A5F5 is a wonderful shade of blue.

**Comment by Wferr** [comment]
Tonight I'll show you how I am generating the theme so you can start messing around with it

**Comment by Wferr** [comment]
128ef2 is the color right now

**Comment by cstill** [comment]
gj
